[book]
title = "ðŸ”° NeoBASIC Programmer's Reference Manual"
description = "The NeoBASIC Programming Language"
language = "en"
src = "src"
authors = [
  "Raul Bras",
  "Contributions from the NeoBASIC Community"
]

[output.html]
theme = "theme"
